### ISSUE TITLE
Inconsistent formating for shortcuts

### ISSUE THREAD

**Issue by YeldhamDev** [godotengine/godot-docs#3249]
The way keyboard shortcuts are displayed in docs is very inconsistent, some examples:

- Ctrl D
- Ctrl+D
- Ctrl + D
- (Ctrl + D)
- `Ctrl + D`
- <kbd>Ctrl</kbd> <kbd>D</kbd> (Which doesn't show in the actual docs.)

**Comment by pycbouh** [comment]
The last one is the most visually pleasing, so I'd stick with that.

We need to consider, that macOS often has different default shortcuts than other platforms (#3244), which is not displayed properly throughout the docs. So if we do some big change to shortcut formatting, it makes sense to fix both problems together (with some formatting macros probably?).

**Comment by YeldhamDev** [comment]
> The last one is the most visually pleasing, so I'd stick with that.

The problem is that, like I said, it doesn't actually show in the docs, appearing just as `<kbd></kbd>` instead.

**Comment by pycbouh** [comment]
Okay, so I'd stick with that, *and investigate, why does it not work currently*. 😏

I'll take a look at that problem later.

**Comment by pycbouh** [comment]
So, I poked around, and seems that `<kbd>` tag is working perfectly fine, but it is almost never used. Looking through the codebase, only three articles refer to it:

![image](https://user-images.githubusercontent.com/11782833/76202397-ceaca180-6205-11ea-863f-59566c347dce.png)

First one being the same as @YeldhamDev described, because somebody simply put the html tag as a plain text. This does not work, obviously, and the end result is thus:

![image](https://user-images.githubusercontent.com/11782833/76202479-f3087e00-6205-11ea-8473-81bd6a0cb3d9.png)
*from [GDScript style guide](https://docs.godotengine.org/en/stable/getting_started/scripting/gdscript/gdscript_styleguide.html#comment-spacing)*

The other two articles are properly using the `:kbd:` macro like so:
```
:kbd:`F1`
```

This results in a correctly generated HTML, but there are no CSS rules associated with it, so the end result is unnoticable (only font differs, there is a rule that sets it to monospaced):
```html
<kbd class="kbd docutils literal notranslate">F1</kbd>
```

![image](https://user-images.githubusercontent.com/11782833/76202885-a7a29f80-6206-11ea-8b91-532b96181bc0.png)
*from [Control the game’s UI with code](https://docs.godotengine.org/en/stable/getting_started/step_by_step/ui_code_a_life_bar.html#fade-the-bar-when-the-player-dies)*

There is [this PR](https://github.com/readthedocs/sphinx_rtd_theme/pull/677) in RTD repo from 2018, but Godot Docs don't seem to have it. I have no idea, if and how theme changes are pulled into Godot Docs, though.

On a bright side, this can be easily fixed with `custom.css` rule anyway, because HTML is already there. Here is an example of GitHub styles applied directly to the light theme and my quick attempt at adjusting it for the dark theme:

### Light Theme
![image](https://user-images.githubusercontent.com/11782833/76201673-a8d2cd00-6204-11ea-9232-2f0378583ca8.png)

Source:
```css
kbd, .kbd {
    display: inline-block;
    padding: 3px 5px;
    font-size: 11px;
    line-height: 10px;
    color: #444d56;
    vertical-align: middle;
    background-color: #fafbfc;
    border: 1px solid #d1d5da;
    border-radius: 3px;
    box-shadow: inset 0 -1px 0 #d1d5da;
}
```

### Dark Theme
![image](https://user-images.githubusercontent.com/11782833/76202255-9a38e580-6205-11ea-94e8-6ec45fb28944.png)

Source:
```css
kbd, .kbd {
    display: inline-block;
    padding: 3px 5px;
    font-size: 11px;
    line-height: 10px;
    color: #98cdf5;
    vertical-align: middle;
    background-color: #595b5d;
    border: 1px solid #43484c;
    border-radius: 3px;
    box-shadow: inset 0 -1px 0 #1e2023;
}
```

-----

Now, I can make a PR, that adds this and look through sources replacing every instance of a shortcut being mentioned with a proper macro, but I have to know, if we are going with
* <kbd>Ctrl</kbd> + <kbd>Alt</kbd>
* <kbd>Ctrl</kbd> - <kbd>Alt</kbd>
* <kbd>Ctrl</kbd> <kbd>Alt</kbd>
* <kbd>Ctrl+Alt</kbd>
* <kbd>Ctrl-Alt</kbd>
* <kbd>Ctrl Alt</kbd>
* something else?

And there is a withstanding issue about macOS shortcuts, though if no fancy solution is available we can at least mark them down like so:
> Press <kbd>F1</kbd> (Win, Linux) / <kbd>Alt</kbd> <kbd>1</kbd> (macOS) to open 2D editor

or so
> Press <kbd>F1</kbd> (or <kbd>Alt</kbd> <kbd>1</kbd> on macOS) to open 2D editor
