### ISSUE TITLE
Dark mode responsive documentation images, diagrams

### ISSUE THREAD

**Issue by hazarek** [godotengine/godot-docs#3861]
**Issue description:**
Some doc images are not compatible with dark mode.

**URL to the documentation page:**
Two pages I randomly selected.
https://docs.godotengine.org/en/stable/development/cpp/inheritance_class_tree.html
https://docs.godotengine.org/en/stable/_images/signals.png

## PNG diagrams that should be adaptive SVG.
![example1](https://user-images.githubusercontent.com/36481442/89134043-51722800-d52a-11ea-90ec-2605596141de.png)
![cap 4](https://user-images.githubusercontent.com/36481442/89134191-afebd600-d52b-11ea-8538-eb5cabc73905.png)

## White opaque PNG screenshots that should be transparent.
Some png files have a white opaque background, for example;

![cap 5](https://user-images.githubusercontent.com/36481442/89134028-225bb680-d52a-11ea-8c47-463df28e56cd.png)
![cap 2](https://user-images.githubusercontent.com/36481442/89134079-bb8acd00-d52a-11ea-8ce2-d49b9775adaa.png)

## Solution is Adaptive SVG (prefers-color-scheme)
I exported the [this](https://docs.godotengine.org/en/latest/_images/Object.png) GraphML file as SVG and I wrote inline CSS.
```css
<style>
    #background {fill: #FCFCFC;}
    #boxes{fill: #C3E3FF; stroke:white;}
    #objectbox{fill:#7BCAFF;}
    #arrows{fill: #599DD6;stroke: #599DD6;}
    text{
        fill: #404040;
        stroke:none;
        font-family: 'Lucida Sans', 'Lucida Sans Regular', 'Lucida Grande', 'Lucida Sans Unicode', Geneva, Verdana, sans-serif;
        font-size: 12px;
        text-align: center;
    }
    @media (prefers-color-scheme: dark) {
    text{
        fill:white;
        }
    #background {fill: #2E3236;}
    #boxes{fill:#4d6680;stroke: #2E3236;}
    #objectbox{fill:#6C99C4;}
    #arrows{
            stroke: #417DA9;
            fill:#417DA9;
            stroke-width:2px;
      }
    }
  </style>
```
See SVG below. You can see the change by toggle between the light / dark mode of your operating system;

<a href='https://svgshare.com/s/NTQ' ><img src='https://svgshare.com/i/NTQ.svg' title='' /></a>

Before / After demo gif;

![o](https://user-images.githubusercontent.com/36481442/89134351-1c1b0980-d52d-11ea-970a-a18877d9280d.gif)

## Embeded PNG screenshot in adaptive SVG
This can be transparent PNG with red stokes and labels or SVG + Embedded PNG + CSS. See SVG The font may look different to you because it is not defined in html. you need to have Montserrat installed on your system. example below; 

<a href='https://svgshare.com/s/NSD' ><img src='https://svgshare.com/i/NSD.svg' title='' /></a>
https://gist.github.com/hazarek/e4dd3f981715374b7c67b4bfaddf9a21

If SVG is used, styles, fonts, colors can be changed dynamically. The same style should be used for all screenshots. for example my screenshot style template;
```css
            g.labels {
            fill:#BE5460;
            font-family: 'Montserrat', sans-serif;
            font-weight: 600;
            font-size: 6pt;
            }
            g.strokes {
                stroke:#BE5460;
                fill: none;
                stroke-width: 3px;
            }
```

## What should be done.

- [ ] All diagrams that can be converted into vector will be responsive SVG.
- [ ] Opaque screenshots will be adapted to dark mode.

related issue - > https://github.com/godotengine/godot-docs/issues/3390
