### ISSUE TITLE
"ref" badge is duplicated in instant search results

### ISSUE THREAD

**Issue by Calinou** [godotengine/godot-docs#4338]
#4307 introduced badges for class reference links, but the badge is displayed twice in the "instant search" results:

![image](https://user-images.githubusercontent.com/180032/98168332-b9019000-1eea-11eb-8925-1a8ea016defd.png)

**Comment by pycbouh** [comment]
It's not duplicated, it's from the next line:

![image](https://user-images.githubusercontent.com/11782833/98171609-11dc2300-1f01-11eb-8cd3-da79809c7179.png)

**Comment by pycbouh** [comment]
Something like this, maybe?

```css
.wy-body-for-nav .search__result__single a[href*="classes/"]::before {
    display: none;
}
.wy-body-for-nav .search__result__single a[href*="classes/"]:first-child::before {
    display: inline;
}
```

It would look like [this](https://user-images.githubusercontent.com/11782833/98240935-4096df80-1f7b-11eb-963c-8dc1b854e773.png). But I'm not sure if there are any other permutations/cases where this won't work in the instant search results.
